Develop
YaminoJakkaru/java-filmorate pull request #22
Opened 2023-02-20 22:16 UTC by YaminoJakkaru

2023-02-21 10:57 UTC, LexLippi requested changes
Привет!

1. Не помешало бы README с описанием тех задач, которые были выбраны. Так и мне проще проверять, и проект выглядит солиднее, сразу видно, что сделано. Опционально к каждому пункту можно добавить описание, как было реализовано, почему выбран такой подход, почему выбрали именно это задание `etc.`

2. Хорошая работа, но есть замечания, которые необходимо исправить. По поводу исправлений подзапросов на `join` советую обратиться к наставнику.

Желаю удачи!!!

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/rowMapper/EventMapper.java
> +public class EventMapper implements RowMapper<Event> {
Аналогичо, можно использовать `enum`

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/ReviewDbService.java
> +    private static final int UPDATE = 3;
Для этого тоже стоит завести `enum`, чтобы вот так где-то в произвольном месте кода не перечислять идентификаторы

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/ReviewDbService.java
> +        review=reviewStorage.changeReview(review);
Честно говоря, я противник изменения переменных, особенно в этом случае. 
Ничего не мешает нам завести новую локальную переменную, например

Это необязательно править, просто надо понимать, что любое переприсваивание значения в переменную усложняет работу с кодом, так как нам необходимо не забывать, что значение в этой переменной может измениться на совершенно другое

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/EventDbStorage.java
> +        jdbcTemplate.update(query, userId, entityId, eventType, operation,
Про `timestamp`:

1. Лучше так не называть поле, а например использовать `created_at`
2. Можно не использовать здесь явную вставку, а в субд добавить дефолтное значение, `now()` или `current_timestamp`, например, для некотороых полей это бывает полезно

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/EventDbStorage.java
> +                + " order by timestamp";
лучше явно в запросе прописать `asc` или `desc` порядок, чтобы потом не путаться

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            " where fg.film_id = f.film_id) as genres_names," +
Не допускаются запросы с вложенными подзапросами, необходимо использовать `join`

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +                "where director_id in(select director_id from film_director where film_id=" + film.getId() + ")";
Аналогичное замечание про вложенные запросы

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            query += GROUP_BY_ID_CLAUSE + ORDER_BY_COUNT_CLAUSE + " limit " + count;
Лучше не использовать синтаксис `limit`, так как он не указан в стандарте `SQL` и его реализация - прерогатива конкретнйо СУБД. Его стандартным аналогом является оператор `fetch`

https://www.cybertec-postgresql.com/en/postgresql-limit-vs-fetch-first-rows-with-ties/

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +    }
Снова обращаю внимание на подзапросы

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            String sqlQuery = "insert into film_director (film_id,director_id) values (?,?)";
Почему где-то используется `insertOperations`, а где-то просто `update`, лучше использовать единообразный подход везде

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            query += " or lower(f.name) like '%" + searchQuery + "%'";
можно использовать оператор `ilike`, он сравнивает игнорируя регистр

2023-02-21 10:57 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorageValidator.java
> +        return jdbcTemplate.queryForObject(queryCheck, Integer.class) == 2;
Почему такая константа?

2023-02-21 12:16 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS film_director
можно не исправлять

2023-02-21 13:30 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/ReviewDbService.java
> +    private static final int UPDATE = 3;
исправлено

2023-02-21 13:30 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/ReviewDbService.java
> +        review=reviewStorage.changeReview(review);
исправлено

2023-02-21 13:30 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/EventDbStorage.java
> +        jdbcTemplate.update(query, userId, entityId, eventType, operation,
исправлено

2023-02-21 13:30 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/EventDbStorage.java
> +                + " order by timestamp";
исправлено

2023-02-21 13:31 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorageValidator.java
> +        return jdbcTemplate.queryForObject(queryCheck, Integer.class) == 2;
исправлено

2023-02-21 13:50 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/DirectorDbService.java
> +@Qualifier("DirectorDbService")
исправлено

2023-02-21 13:50 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
> +    CONSTRAINT film_fk FOREIGN KEY (film_id) REFERENCES film
исправлено

2023-02-21 13:51 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
> +    entity_id int NOT NULL,
исправлено

2023-02-21 13:51 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
> +    is_positive    boolean                           ,
написать описание

2023-02-21 14:42 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/DirectorDbService.java
> +    private static final Logger LOG = LoggerFactory.getLogger(UserService.class);
исправлено

2023-02-21 14:42 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/DirectorDbService.java
> +        if (director.getName().isEmpty() || director.getName().isBlank()) {
исправлено

2023-02-21 14:42 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/DirectorDbService.java
> +        if (director.getName().isEmpty() || director.getName().isBlank()) {
исправлено

2023-02-21 14:43 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorDbStorage.java
> +    SimpleJdbcInsert simpleJdbcInsertDirector;
исправлено

2023-02-21 14:43 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorDbStorage.java
> +        simpleJdbcInsertDirector = new SimpleJdbcInsert(jdbcTemplate)
исправлено

2023-02-21 14:43 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/model/Director.java
> +        return values;
исправлено

2023-02-21 14:44 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            query += GROUP_BY_ID_CLAUSE + ORDER_BY_COUNT_CLAUSE + " limit " + count;
исправлено

2023-02-21 14:49 UTC, yayayii commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            query += " or lower(f.name) like '%" + searchQuery + "%'";
исправлено

2023-02-21 17:06 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +            " where fg.film_id = f.film_id) as genres_names," +
исправлено

2023-02-21 17:20 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +                "where director_id in(select director_id from film_director where film_id=" + film.getId() + ")";
исправлено

2023-02-21 19:54 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorDbStorage.java
> +        List<Director> director = jdbcTemplate.query(query, new DirectorMapper());
bcghfdktyj

2023-02-21 19:55 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/rowMapper/DirectorMapper.java
> +public class DirectorMapper implements RowMapper<Director> {
исправлено

2023-02-21 21:03 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS user_friend
исправлено

2023-02-22 15:54 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +    }
1)исправлено
2) получено разрешение не исправлять

2023-02-22 15:54 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
> +    is_positive    boolean                           ,
исправлено

2023-02-22 15:54 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/rowMapper/DirectorMapper.java
> +public class DirectorMapper implements RowMapper<Director> {
исправлено

2023-02-22 15:55 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorDbStorage.java
> +        List<Director> director = jdbcTemplate.query(query, new DirectorMapper());
исправлено

2023-02-22 16:30 UTC, YaminoJakkaru commented on src/main/resources/schema.sql
>  CREATE TABLE IF NOT EXISTS user_friend
исправлено

2023-02-22 16:31 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/rowMapper/EventMapper.java
> +public class EventMapper implements RowMapper<Event> {
исправлено

2023-02-23 05:23 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/ReviewDbService.java
> +    private static final int UPDATE = 3;
исправлено

2023-02-23 05:23 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorDbStorage.java
> +        return director.get(0);
в таком случае мы теряем log

2023-02-23 09:24 UTC, LexLippi requested changes
Привет!

Есть пара мелких замечаний, а в целом работа очень хорошая!

Желаю удачи!!!

2023-02-23 09:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getReviews(@RequestParam (defaultValue = "0") int filmId,
А точно здесь нужно `defaultValue`, да к тому же 0, который не является валидным идентификатором

2023-02-23 09:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/dbService/DirectorDbService.java
> +public class DirectorDbService implements DirectorService {
Этот комментарий можно не исправлять, просто чаще всего сервис не должен зависеть от конкретной реализации `Storage`, часто бывает необходимо подсовывать разные реализации в один и тот же объект.

И создавать копии `Service`, не изменяя его код, например для кэширования данных.

Поэтому лучше не использовать в названии сервисов `Db`, потому что сервису должно ыть не интересно с какой именно реализацией хранилища он работает.

Это касается всех сервисов, но напишу только здесь, чтобы не дублировать комментарии

2023-02-23 09:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/DirectorDbStorage.java
> +        return director.get(0);
Не обязательно

```java
return jdbcTemplate.query("select * from director where director_id=" + id, 
                           DirectorMapper.INSTANCE)
                       .stream()
                       .findFirst()
                       .orElseThrow(() -> {
                           LOG.warn("Попытка получить несуществующего режиссера");
                           return new NotFoundException();
                       });
```

2023-02-23 09:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        review.setReviewId(reviewId);
40 и 42 строчки немного противоречат друг другу.
В 40 мы обновляем локальную переменную с которой больше ничего не делаем (хотя вроде бы можем ее вернуть в качестве результат)
В 42 мы делаем запрос к СУБД, забивая на то, что делали в 40 строчке

2023-02-23 09:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        return reviews.get(0);
Здесь можно аналогично ситуации с режиссерами поступить

2023-02-23 09:24 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        String query2 = "insert into review_dislike(review_id, user_id) values (?, ?)";
А почему не просто `query`? 
:)

2023-02-23 10:12 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/controller/ReviewController.java
> +    public List<Review> getReviews(@RequestParam (defaultValue = "0") int filmId,
исправлено

2023-02-23 10:17 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        review.setReviewId(reviewId);
исправлено

2023-02-23 10:19 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        return reviews.get(0);
исправлено

2023-02-23 10:19 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        String query2 = "insert into review_dislike(review_id, user_id) values (?, ?)";
исправлено

2023-02-23 10:19 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/ReviewDbStorage.java
> +        review.setReviewId(reviewId);
исправлено

2023-02-24 10:14 UTC, LexLippi approved these changes
Привет!

Отличная работа!
Мне очень понравилась ваша реализация группового проекта!

Желаю всем удачи в следующих спринтах!

2023-02-24 10:14 UTC, LexLippi approved these changes

2023-03-07 08:03 UTC, merged