Add database
YaminoJakkaru/java-filmorate pull request #4
Opened 2023-01-31 08:35 UTC by YaminoJakkaru

2023-02-01 07:32 UTC, LexLippi requested changes
Привет!

Неплохая работа, но есть некоторое количество замечаний, которые необходимо исправить!

Желаю удачи!

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +    private static final Logger log = LoggerFactory.getLogger(UserStorage.class);
Такие константы обычно называют заглавными буквами

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +            jdbcTemplate.queryForList(queryFriends, Integer.class).forEach(user::addFriend);
В идеале делать как можно меньше запросов к СУБД.

Здесь можно вместо `n+1` запросов сократить количество до `1` запроса, что довольно существенно, надо просто присоединить таблицу друзей к таблице пользователей, и сгруппировать по полям пользователя.

Это существенно увеличит скорость работы данного метода, причём, как алгоритмически, так и сточки зрения взаимодействия с СУБД

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +        log.warn("Запрошен список пользователей");
Почему `warn`?

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +        } catch (IndexOutOfBoundsException e) {
В данном случае я бы воспользовался проверкой результирующего списка на пустоту, так как проверка работает быстрее, чем исключение

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +        SimpleJdbcInsert simpleJdbcInsertFilm = new SimpleJdbcInsert(jdbcTemplate)
1. Почему `insertFilm`?
2. Точно ли мы хотим каждый раз создавать данный `inserter`? Это затратная операция, лучше создать его один раз в конструкторе класса и сохранить в некоторое поле.

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +        return findUserById(userId);
Зачем поиск осуществлять?

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +        }
Это лишнее, не надо делать запрос, метод `update` возвращает количество строк на которые он повлиял. Таким образом если количество равно 0, то можно бросать это исключение. Это ускорит наш метод

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/SupportiveDbStorage.java
> +public class SupportiveDbStorage {
1. Хранилище без интерфейса - плохо
2. Не стоит обощать хранилища для вспомогательных данных. Это нарушает Interface Segregation Principle из принципов SOLID

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +public class FilmDbStorage implements FilmStorage {
Замечания аналогичные `UserDbStorage`

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/reader/Reader.java
> +public class Reader {
Опять же для каждого класса лучше завести свой `RowMapper`, для `RowMapper` в `Spring` есть специальный интерфейс

2023-02-01 07:32 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/id/Id.java
> +    private int Id = 0;
С заглавной обычно не называем поля класса

2023-02-01 10:31 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +            jdbcTemplate.queryForList(queryFriends, Integer.class).forEach(user::addFriend);
Здравствуйте, я не понимаю как реализовать запрос, у таблицы users и у таблицы user_friend связь один ко многим ,как можно сгруппировать данные по пользователю?

2023-02-01 10:39 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +        return findUserById(userId);
извините, но разве не нужно проверить что данные сохранились верно , если так то можно вернуть просто полученный  user с новым id?

2023-02-01 18:38 UTC, YaminoJakkaru commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/UserDbStorage.java
> +            jdbcTemplate.queryForList(queryFriends, Integer.class).forEach(user::addFriend);
все , я разобрался - group_concat

2023-02-05 11:15 UTC, LexLippi requested changes
Привет!

Остались некоторые замечания, они общие для всех классов, но я везде их писать не стал, где увидишь аналогичные замечания, можешь поправить!

Желаю удачи!!!

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final FilmService filmService;
1. Зачем нам обе этих абстракции? Схема должна быть примерно такая:

```
HTTP-query -> Controller -> Service -> Storage
```

2. `Service` не должен иметь префикс `Db`, он не должен знать, кроме `Qualifier` для `Storage`, какой тип хранилища мы используем. Логика сервиса должна быть универсальной

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    public FilmController(@Qualifier("FilmDbStorage") FilmStorage filmStorage, @Qualifier("FilmDbService") FilmService filmService) {
Зачем два раза `Qualifier`?

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    @GetMapping("/films")
Стоит вынести общую часть в `RequestMapping`. В данном, случае общая часть - `/films`

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/controller/GenreController.java
> +    private final GenreStorage genreStorage;
Здесь должен быть слой сервиса

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/rowMapper/FilmMapper.java
> +                id(resultSet.getInt("film_id"))
Если везде по точке переносишь, то здесь лучше также делать

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/rowMapper/FilmMapper.java
> +            }
Это точно надо внутри предыдущего условного оператора делать?
Кажется, что можно сократить уровень вложенности

2023-02-05 11:15 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/DAO/FilmDbService.java
> +    private final JdbcTemplate jdbcTemplate;
Сервис не должен использовать эту абстракцию

2023-02-07 08:03 UTC, LexLippi requested changes
Привет!

Хорошая работа!
Осталось ещё пару комментариев!

Желаю удачи!

2023-02-07 08:03 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +        String queryCheck = "select user_id from users where user_id=" + userId;
Для таких целей можно использовать другие хранилища, чтобы не плодить одинаковые строки с потенциально одинаковыми ошибками

2023-02-07 08:03 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/storage/DAO/FilmDbStorage.java
> +        String queryCheck = "select user_id from users where user_id=" + userId;
На самом деле, эту валидацию тоже лучше вынести в сервис. Это самый корректный вариант, когда сервис использует несколько хранилищ

2023-02-09 07:06 UTC, LexLippi approved these changes
Привет!

Посмотрел работу, все, в целом ок. Но в идеале `Service` должны быть интерфейсами, и у них должны быть разные реализации соответственно. Сейчас, я работу приму, но к следующему спринту уже буду требовать доработку с интерфейсами!

Желаю удачи!!!

2023-02-09 07:06 UTC, LexLippi commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +@Qualifier("UserDbService")
Пока не уверен в необходимости этой аннотации

2023-02-13 12:37 UTC, merged